#!/bin/sh

#Link Logs
mkdir -p /usr/vpnserver/log
ln -sf /usr/vpnserver/*_log /usr/vpnserver/log

#Link Configs
mkdir -p /etc/vpnserver
ln -sf /etc/vpnserver/vpn_server.config /usr/vpnserver/vpn_server.config

exec /usr/vpnserver/vpnserver execsvc
exit $?
